"use client";
import {type ComponentPropsWithoutRef,type CSSProperties,type MutableRefObject,forwardRef,useCallback,useEffect,useRef,useState} from "react";

export type HolographicVariant="spectral-film"|"brushed-foil"|"thin-film"|"facet-chrome";
export type MotionPermission="idle"|"requesting"|"granted"|"denied"|"unavailable";
export type HolographicTelemetry={permission:MotionPermission;signal:"waiting"|"live"|"stale";source:"none"|"orientation"|"motion"|"pointer";alpha:number|null;beta:number|null;gamma:number|null;events:number;hz:number;age:number|null;normal:[number,number,number];secure:boolean};
export type HolographicMotion={matrix:MutableRefObject<Float32Array>;telemetry:HolographicTelemetry};

const PRESETS:Record<HolographicVariant,{method:number;material:[number,number,number,number]}>= {
 "spectral-film":{method:0,material:[.08,.72,.11,.55]},"brushed-foil":{method:1,material:[.46,.48,.23,.82]},
 "thin-film":{method:2,material:[.78,.62,.18,.32]},"facet-chrome":{method:3,material:[1.18,1.05,.09,1]}
};
const rad=(n:number)=>n*Math.PI/180;
function mul(a:number[],b:number[]){const o=new Array(9).fill(0);for(let r=0;r<3;r++)for(let c=0;c<3;c++)for(let k=0;k<3;k++)o[r*3+c]+=a[r*3+k]*b[k*3+c];return o}
function attitudeMatrix(alpha:number,beta:number,gamma:number,screenAngle:number){const a=rad(alpha),b=rad(beta),g=rad(gamma),s=rad(-screenAngle),ca=Math.cos(a),sa=Math.sin(a),cb=Math.cos(b),sb=Math.sin(b),cg=Math.cos(g),sg=Math.sin(g),cs=Math.cos(s),ss=Math.sin(s);const m=mul(mul(mul([ca,-sa,0,sa,ca,0,0,0,1],[1,0,0,0,cb,-sb,0,sb,cb]),[cg,0,sg,0,1,0,-sg,0,cg]),[cs,-ss,0,ss,cs,0,0,0,1]);return new Float32Array([m[0],m[3],m[6],m[1],m[4],m[7],m[2],m[5],m[8]])}
const normal=(m:Float32Array):[number,number,number]=>[m[6],m[7],m[8]];

export function useHolographicMotion({pointerFallback=true,requestOnFirstInteraction=false,telemetry:trackTelemetry=false}:{pointerFallback?:boolean;requestOnFirstInteraction?:boolean;telemetry?:boolean}={}):HolographicMotion{
 const matrix=useRef(attitudeMatrix(0,0,0,0)),permission=useRef<MotionPermission>("idle"),stats=useRef({events:0,first:0,last:0,lastOrientation:0,lastPaint:0});
 const[telemetry,setTelemetry]=useState<HolographicTelemetry>({permission:"idle",signal:"waiting",source:"none",alpha:null,beta:null,gamma:null,events:0,hz:0,age:null,normal:[0,0,1],secure:true});
 const publish=useCallback((raw:Partial<HolographicTelemetry>,force=false)=>{if(!trackTelemetry)return;const now=performance.now();if(!force&&now-stats.current.lastPaint<80)return;stats.current.lastPaint=now;setTelemetry(old=>({...old,...raw,permission:permission.current,events:stats.current.events,hz:stats.current.events*1000/Math.max(1,now-stats.current.first),age:stats.current.last?Math.round(now-stats.current.last):null,secure:window.isSecureContext}))},[trackTelemetry]);
 const consume=useCallback((alpha:number,beta:number,gamma:number,source:"orientation"|"motion")=>{const angle=((screen.orientation?.angle??Number((window as Window&{orientation?:number}).orientation)??0)+360)%360;matrix.current=attitudeMatrix(alpha,beta,gamma,angle);const now=performance.now();stats.current.events++;stats.current.first ||=now;stats.current.last=now;if(source==="orientation")stats.current.lastOrientation=now;permission.current="granted";publish({signal:"live",source,alpha,beta,gamma,normal:normal(matrix.current)})},[publish]);
 useEffect(()=>{if(trackTelemetry)setTelemetry(v=>({...v,secure:window.isSecureContext}));const orient=(e:DeviceOrientationEvent)=>{if(typeof e.beta==="number"&&typeof e.gamma==="number")consume(typeof e.alpha==="number"?e.alpha:0,e.beta,e.gamma,"orientation")};const motion=(e:DeviceMotionEvent)=>{if(performance.now()-stats.current.lastOrientation<600)return;const g=e.accelerationIncludingGravity;if(!g||typeof g.x!=="number"||typeof g.y!=="number"||typeof g.z!=="number")return;consume(0,Math.atan2(-g.y,g.z)*180/Math.PI,Math.atan2(g.x,Math.hypot(g.y,g.z))*180/Math.PI,"motion")};addEventListener("deviceorientation",orient,true);addEventListener("deviceorientationabsolute",orient as EventListener,true);addEventListener("devicemotion",motion,true);const timer=trackTelemetry?setInterval(()=>{const now=performance.now(),age=stats.current.last?Math.round(now-stats.current.last):null;setTelemetry(v=>({...v,age,signal:age!==null&&age<900?"live":permission.current==="granted"?"stale":"waiting"}))},400):null;return()=>{removeEventListener("deviceorientation",orient,true);removeEventListener("deviceorientationabsolute",orient as EventListener,true);removeEventListener("devicemotion",motion,true);if(timer!==null)clearInterval(timer)}},[consume,trackTelemetry]);
 useEffect(()=>{if(!pointerFallback)return;const move=(e:PointerEvent)=>{if(stats.current.last&&performance.now()-stats.current.last<900)return;const a=(e.clientX/innerWidth-.5)*70,b=(e.clientY/innerHeight-.5)*45,g=a*.45;matrix.current=attitudeMatrix(a,b,g,0);publish({source:"pointer",alpha:a,beta:b,gamma:g,normal:normal(matrix.current)})};addEventListener("pointermove",move,{passive:true});return()=>removeEventListener("pointermove",move)},[pointerFallback,publish]);
 useEffect(()=>{const O=window.DeviceOrientationEvent as typeof DeviceOrientationEvent&{requestPermission?:()=>Promise<"granted"|"denied">},M=window.DeviceMotionEvent as typeof DeviceMotionEvent&{requestPermission?:()=>Promise<"granted"|"denied">};const needsGesture=typeof O?.requestPermission==="function"||typeof M?.requestPermission==="function";if(!needsGesture){permission.current=O?"granted":"unavailable";publish({permission:permission.current},true);return}if(!requestOnFirstInteraction)return;let active=true,requesting=false,settled=false;const cleanup=()=>{removeEventListener("touchend",onGesture,true);removeEventListener("click",onGesture,true);removeEventListener("keydown",onGesture,true)};const request=async()=>{if(!active||requesting||settled)return;requesting=true;permission.current="requesting";publish({permission:"requesting"},true);try{const asks:Promise<"granted"|"denied">[]=[];if(typeof O.requestPermission==="function")asks.push(O.requestPermission());if(typeof M.requestPermission==="function")asks.push(M.requestPermission());const next=(await Promise.all(asks)).every(v=>v==="granted")?"granted":"denied";if(!active)return;permission.current=next;settled=true;cleanup();publish({permission:next,signal:next==="denied"?"stale":"waiting"},true)}catch{if(!active)return;requesting=false;permission.current="idle";publish({permission:"idle",signal:"waiting"},true)}};const onGesture=()=>void request();addEventListener("touchend",onGesture,true);addEventListener("click",onGesture,true);addEventListener("keydown",onGesture,true);void request();return()=>{active=false;cleanup()}},[publish,requestOnFirstInteraction]);
 return{matrix,telemetry};
}

const VS="attribute vec2 position;varying vec2 uv;void main(){uv=position*.5+.5;gl_Position=vec4(position,0.,1.);}";
const FS=["#extension GL_OES_standard_derivatives : enable","precision highp float;varying vec2 uv;uniform vec2 resolution;uniform mat3 worldFromDevice;uniform vec4 material;uniform vec4 specularParams;uniform float method;","float rr(vec2 p,vec2 b,float r){vec2 q=abs(p)-b+r;return min(max(q.x,q.y),0.)+length(max(q,0.))-r;}","float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}","float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1)),f.x),f.y);}","vec3 spectrum(float t){return pow(.5+.5*cos(6.28318*(t+vec3(0,.67,.33))),vec3(1.35));}","float ggx(float n,float r){float a=r*r,a2=a*a,d=n*n*(a2-1.)+1.;return a2/(3.14159*d*d);}","vec3 env(vec3 r){vec3 c=mix(vec3(.012,.014,.019),vec3(.095,.105,.125),smoothstep(-.35,.7,r.y));c+=exp(-pow(abs(r.y+.08)*7.,2.))*vec3(.1,.115,.13);vec3 d=normalize(vec3(-.32,.72,.61));c+=pow(max(dot(r,d),0.),46.)*vec3(.56,.6,.64)+pow(max(dot(r,d),0.),240.)*vec3(2.4,2.15,1.8);c+=pow(max(dot(r,normalize(vec3(.88,.05,.47))),0.),90.)*vec3(.32,.08,.13)+pow(max(dot(r,normalize(vec3(-.86,-.12,.5))),0.),110.)*vec3(.06,.13,.27);return c;}",
"void main(){vec2 p=uv-.5;float a=resolution.x/resolution.y;p.x*=a;float d=rr(p,vec2(a*.488,.465),.43),aa=max(fwidth(d)*1.5,.0015),al=1.-smoothstep(-aa,aa,d);if(al<.01)discard;vec2 gd=normalize(vec2(dFdx(d),dFdy(d))+.00001);float inward=max(-d,0.),rm=1.-smoothstep(.095,.12,inward),rp=clamp(inward/.095,0.,1.)*6.28318,rh=-sin(rp)*rm,rs=-cos(rp)*rm,grain=noise(uv*vec2(720,115)),brush=sin(uv.x*1380.+noise(uv*vec2(7,29))*8.);vec2 micro=vec2(0);if(method>.5&&method<1.5)micro=vec2(brush*.010,dFdy(grain)*.08);if(method>1.5&&method<2.5)micro=vec2(dFdx(noise(uv*vec2(16,9))),dFdy(noise(uv*vec2(16,9))))*.035;vec2 cell=floor(uv*vec2(24,7));if(method>2.5)micro=(vec2(hash(cell),hash(cell+7.31))-.5)*.075;vec3 shapeN=normalize(vec3(p.x*.18,p.y*.38,1)),n=normalize(vec3(shapeN.xy+gd*rs*.78+micro,1.-abs(rh)*.18)),nw=normalize(worldFromDevice*n),vw=normalize(worldFromDevice*vec3(0,0,1)),rw=normalize(reflect(-vw,nw)),l=normalize(vec3(-.12,-.66,.74)),l2=normalize(vec3(.72,-.12,.68)),h=normalize(l+vw);float ndl=max(dot(nw,l),0.),ndl2=max(dot(nw,l2),0.),ndv=max(dot(nw,vw),.001),rough=clamp(material.z*.55+(grain-.5)*.012,.05,.16),spec=ggx(max(dot(nw,h),0.),rough)*ndl*.42,fres=.18+.82*pow(1.-ndv,5.),inc=dot(nw,l);vec3 e=env(rw),metal;if(method<.5){float sweep=dot(rw,normalize(vec3(.76,.18,.62)))*.58+rw.y*.16+.08;metal=e*.46+spectrum(sweep)*(.68+fres*.42)+vec3(spec)*.72;}else if(method<1.5){float streak=.5+.5*sin(uv.x*920.+noise(uv*vec2(8,37))*5.),glint=pow(streak,18.);vec3 petrol=vec3(.018,.055,.068)+spectrum(dot(rw,normalize(vec3(.82,.08,.56)))*1.72+.46)*.24;metal=e*.72+petrol*(.52+.34*ndl)+glint*spectrum(uv.x*.4+inc)*.34+vec3(spec)*1.12;}else if(method<2.5){float optical=(1.-abs(inc))*1.58+noise(uv*vec2(5,3))*.07+.18;vec3 pearl=.72+.20*cos(6.28318*(optical*vec3(1,1.29,1.61)+vec3(.02,.24,.51)));metal=e*.31+pearl*(.64+fres*.48)+vec3(spec)*.58;}else{float band=dot(rw,normalize(vec3(.67,.29,.68)))*3.15+hash(cell)*.18;vec3 prism=spectrum(band);metal=e*1.02+prism*(.48+.62*(.42+.58*pow(.5+.5*cos(6.28318*band),5.)))+vec3(spec)*1.48;}float sl=ndl,sh=max(dot(nw,h),0.),surfaceF=.04+.96*pow(1.-ndv,5.),surfaceR=specularParams.y,gloss=1.-smoothstep(.025,.25,surfaceR),glass=min(ggx(sh,surfaceR)*sl*.032,3.2),pin=pow(sh,mix(72.,260.,gloss))*mix(.45,1.5,gloss),bloom=pow(sh,mix(24.,54.,gloss))*specularParams.z;vec3 surfaceSpec=vec3(1.,.985,.965)*(glass+pin)+vec3(.72,.82,1.)*bloom;metal+=surfaceSpec*specularParams.x*mix(1.,surfaceF,specularParams.w)+e*surfaceF*.10*specularParams.x+ndl2*vec3(.075,.025,.045);float raised=max(rh,0.),recessed=max(-rh,0.);metal+=raised*(env(rw)*1.25+.13);metal*=1.-recessed*.34;metal+=pow(max(rs,0.),6.)*.30;metal*=1.-dot(uv-.5,uv-.5)*.34;metal=metal/(metal+.78);gl_FragColor=vec4(pow(max(metal,0.),vec3(.86)),al);}"].join("\n");
function compile(gl:WebGLRenderingContext,type:number,src:string){const s=gl.createShader(type)!;gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s)||"Shader compile failed");return s}

const bounded=(value:number,fallback:number,min:number,max:number)=>Number.isFinite(value)?Math.min(max,Math.max(min,value)):fallback;
export type HolographicButtonProps=ComponentPropsWithoutRef<"button">&{motion:Pick<HolographicMotion,"matrix">;variant?:HolographicVariant;width?:CSSProperties["width"];height?:CSSProperties["height"];specularIntensity?:number;specularRoughness?:number;specularBloom?:number;specularFresnel?:number};
export const HolographicButton=forwardRef<HTMLButtonElement,HolographicButtonProps>(function HolographicButton({motion,variant="spectral-film",children="ACTIVATE",width,height,specularIntensity=1,specularRoughness=.06,specularBloom=.14,specularFresnel=.22,className="",style,type="button",...props},ref){
 const canvas=useRef<HTMLCanvasElement>(null),specular=useRef(new Float32Array([1,.06,.14,.22])),[error,setError]=useState(false),preset=PRESETS[variant];
 specular.current[0]=bounded(specularIntensity,1,0,3);specular.current[1]=bounded(specularRoughness,.06,.025,.3);specular.current[2]=bounded(specularBloom,.14,0,1);specular.current[3]=bounded(specularFresnel,.22,0,1);
 useEffect(()=>{const c=canvas.current;if(!c)return;let raf=0;try{const gl=c.getContext("webgl",{alpha:true,antialias:true,premultipliedAlpha:true});if(!gl){setError(true);return}gl.getExtension("OES_standard_derivatives");const p=gl.createProgram()!;gl.attachShader(p,compile(gl,gl.VERTEX_SHADER,VS));gl.attachShader(p,compile(gl,gl.FRAGMENT_SHADER,FS));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||"Program link failed");gl.useProgram(p);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const pos=gl.getAttribLocation(p,"position");gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);const ur=gl.getUniformLocation(p,"resolution"),um=gl.getUniformLocation(p,"worldFromDevice"),umat=gl.getUniformLocation(p,"material"),us=gl.getUniformLocation(p,"specularParams"),ume=gl.getUniformLocation(p,"method");gl.uniform4f(umat,...preset.material);gl.uniform1f(ume,preset.method);const draw=()=>{const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(c.width!==w||c.height!==h){c.width=w;c.height=h;gl.viewport(0,0,w,h)}gl.uniform2f(ur,w,h);gl.uniformMatrix3fv(um,false,motion.matrix.current);gl.uniform4fv(us,specular.current);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.drawArrays(gl.TRIANGLES,0,6);raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>cancelAnimationFrame(raf)}catch{setError(true)}},[motion.matrix,preset]);
 const layoutStyle:CSSProperties={...style,...(width!==undefined?{width}:{}),...(height!==undefined?{height}:{})};
 return <button ref={ref} type={type} className={`holo-button ${className}`.trim()} style={layoutStyle} {...props}><span className="holo-button__shadow"/><span className="holo-button__body">{error?<span className="holo-button__error">WEBGL UNAVAILABLE</span>:<canvas ref={canvas}/>}<span className="holo-button__copy"><b>{children}</b></span></span></button>
});
